In [7]:
# Importamos la librería pandas y optbinning
import pandas as pd
from sklearn.model_selection import train_test_split
from optbinning import Scorecard, BinningProcess, OptimalBinning

In [8]:
# Imnportamos el conjunto de daros "germacredit"
dt=pd.read_csv('germancredit.csv')

In [9]:
#Recodifico esta variable creditability (variable objetivo) para que sea binaria
dt.rename(columns={"creditability":"y"},inplace=True)
dt['y'] = dt['y'].replace(['good', 'bad'], [0,1])

C:\Users\naira\AppData\Local\Temp\ipykernel_20320\2540553216.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  dt['y'] = dt['y'].replace(['good', 'bad'], [0,1])

In [10]:
# Creo la muestra de entrenamiento y de test
dt_train, dt_test = train_test_split(dt, stratify= dt["y"], test_size=.25, random_state=1234)

In [11]:
# Realizamos la trimificación optima de age.in.years
variable="age.in.years"
X=dt_train[variable].values
Y=dt_train['y'].values
optb = OptimalBinning(name=variable, dtype="numerical", solver="cp")
optb.fit(X, Y)
optb.splits
binning_table = optb.binning_table
binning_table.build()

,Bin,Count,Count (%),Non-event,Event,Event rate,WoE,IV,JS
0,"(-inf, 25.50)",139,0.185333,81,58,0.417266,-0.513292,0.053122,0.006568
1,"[25.50, 29.50)",146,0.194667,100,46,0.315068,-0.070769,0.000989,0.000124
2,"[29.50, 34.50)",137,0.182667,94,43,0.313869,-0.065203,0.000787,0.000098
3,"[34.50, 36.50)",61,0.081333,51,10,0.163934,0.781943,0.041207,0.005024
4,"[36.50, 38.50)",38,0.050667,30,8,0.210526,0.474458,0.010242,0.001268
5,"[38.50, 41.50)",46,0.061333,35,11,0.239130,0.310155,0.005514,0.000686
6,"[41.50, inf)",183,0.244000,134,49,0.267760,0.158722,0.005946,0.000742
7,Special,0,0.000000,0,0,0.000000,0.0,0.000000,0.000000
8,Missing,0,0.000000,0,0,0.000000,0.0,0.000000,0.000000
Totals,,750,1.000000,525,225,0.300000,,0.117806,0.014511